<?php
$title = 'Tytuł strony głównej';
$description = 'Szybki i prosty CMS';
?>
<h1>reprezenter CMS</h1>
<p>Reprezenter CMS jest ekstremalnie prostym i szybkim silnikiem strony internetowej.</p>
<h2>Szybkość = wyższa pozycja w google</h2>
<p>Sprawdzaliśmy google page speed insights wychodzi 100%. Zobacz sam: <a href="https://developers.google.com/speed/pagespeed/insights/?hl=pl&url=https%3A%2F%2Fwww.reprezenter.pl%2Fcms">Zobacz jak gogole ocenia reprezenter CMS</a></p>
<h3>Główne funkcje </h3>
<ul>
    <li>brak bazy dancyh</li>
    <li>edycja reści przez panel administracyjny</li>
    <li>brak koneczności instalacji</li>
    <li>prosty w obsłudze</li>
    <li>obłsuga wielu języów</li>
    <li>wbudowany responsywny layout</li>
    <li>mechanizmy pozycjonowania - dynamiczne metatagi</li>
    <li>Działa na każdej wersji PHP od 5.3 do najnowszej</li>
    <li>darmowy do użytku lub wdrożenie za 200 zł</li>
</ul>