<?php
$title = 'CMS - tanie i szybkie strony internetowe';
$description = 'Szybki i prosty CMS, tanie strony www.';
?>
<h1>Szybkie i tanie strony internetowe</h1>
<p>Reprezenter CMS jest prostym i szybkim silnikiem strony internetowej.<br/>
Wykonanie strony internetowej jest tanie, a powstała strona www jest przyjazna dla użytkownika.</p>
<h2>Szybkość = wyższa pozycja w google</h2>
<p>Sprawdzaliśmy google page speed insights wychodzi 100%: <br/>
    <a href="https://developers.google.com/speed/pagespeed/insights/?hl=pl&url=https%3A%2F%2Fwww.reprezenter.pl%2Fcms">Zobacz jak gogole ocenia strony reprezenter CMS</a></p>
<p>Sprawdzaliśmy również zgodność z W3C: <br/>
    <a href="https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.reprezenter.pl%2Fcms">Zobacz zgodność strony ze standardem W3C</a></p>

<h2>Główne funkcje</h2>
<ul>
    <li>brak bazy danych</li>
    <li>edycja treści przez panel administracyjny lub w plikach html.</li>
    <li>brak konieczności instalacji</li>
    <li>prosty w obsłudze</li>
    <li>obsługa wielu języków</li>
    <li>wbudowany responsywny layout</li>
    <li>mechanizmy pozycjonowania - dynamiczne metatagi</li>
    <li>Działa na każdej wersji PHP od 5.3 do najnowszej</li>
    <li>darmowy do użytku lub tanie wdrożenie prostej strony internetowej</li>
</ul>

<h2>Kod źródłowy i licencja</h2>
<p>Projekt na licencji open source, można pobrać z: <a href="https://github.com/reprezenter/cms">Github</a></p>