<a class="adminBtn" href="/admin/blog/edit.html">Nowy wpis</a>
<br/><br/>
<div classs="blogEntries">
    <?php $entries = $api->getModule('Blog')->getEntries(); ?>
    <?php foreach ($entries['paginator'] as $entry): ?>
        <table class="adminTable">
            <tr>
                <td><img src="/<?php echo $api->getModule('Blog')->getEntryImg($entry['id']); ?>" /></td>
                <td><?php echo $entry['title']; ?></td>
                <td>
                    <a class="adminBtn" href="/admin/blog/edit.html?id=<?php echo $entry['id']; ?>">Edycja</a>
                    <a class="adminBtn confirm" href="/admin/blog/edit.html?id=<?php echo $entry['id']; ?>&del=1">Usuń</a>
                </td>
            </tr>                                  
        </table>                    
    <?php endforeach; ?>
    <?php if ($entries['currentPage'] > 1): ?>
        <a href="/admin/blog/index.html?page=<?php echo $entries['currentPage'] - 1; ?>">Poprzednia</a>
    <?php endif; ?>
    <?php if ($entries['pagesCount'] > $entries['currentPage']): ?>
        <a href="/admin/blog/index.html?page=<?php echo $entries['currentPage'] + 1; ?>">Następna</a>
    <?php endif; ?>

</div>