<?php $entry = $api->getModule('Blog')->getEntryByUrl() ?>
<?php if ($entry): ?>
    <?php var_dump($entry); ?>
    <img src="/<?php echo $api->getModule('Blog')->getEntryImg($entry['id']); ?>" />
<?php else: ?>
    <h1>Blog entries</h1>
    <div classs="blogEntries">
        <?php $entries = $api->getModule('Blog')->getEntries(); ?>
        <?php foreach ($entries as $entry): ?>
            <a href="/blog/<?php echo $entry['slug']; ?>.html"><?php echo $entry['title']; ?></a>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
