<!DOCTYPE html>
<html lang="<?php echo $api->langShort(); ?>">
    <head>
        <meta name="robots" content="index, follow">
        <meta charset="utf-8">
        <title><?php echo $api->getTemplateVars('title'); ?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">        
        <meta name="description" content="<?php echo $api->getTemplateVars('description'); ?>">
        <style>
<?php echo file_get_contents('css/main.css'); ?>
        </style>
        <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon">
        <link rel="icon" href="img/favicon.ico" type="image/x-icon">
    </head>
    <body>
        <div class="contentWrapper">
            <div class="header">
                <div class="logo">
                    <a href="<?php echo $api->getConfig()['baseUrl']; ?>" 
                       title="<?php echo $api->getConfig()['defaultPageTitle']; ?>">
                        <span></span> <?php echo $api->getConfig()['defaultPageTitle']; ?>
                    </a>
                </div>    
                <a class="hamburger" href="#"><img  src="img/hamburger.png" alt="menu" /></a>
                <div class="menu">                
                    <ul>
                        <li><a title="Blog" href="/admin/blog.html">Blog</a></li>
                    </ul>
                </div>
                <div class="clear"></div>
                <?php echo $api->getAuthTemplate(); ?>
            </div>
            <div class="content">
                <?php echo $api->getSessionMsgTemplate(); ?>
                <?php echo $api->getTemplate(); ?>
            </div>
            <div class="footer">
                <p class="copy">Copyright &copy; <?php echo date('Y'); ?> <?php echo $api->getConfig()['defaultPageTitle']; ?></p>
                <p class="developed"><a href="https://www.reprezenter.pl/" target="_blank">reprezenter CMS</a></p>
                <div class="clear"></div>
            </div>
        </div>
        <script src="js/admin/main.js"></script>
    </body>

</html>