
</div>
<div class="footer">
    <p class="copy">Copyright 2020 - <?php echo date('Y'); ?> Wirtalne Biuro</p>
                    <div class="footerMenu">                
                    <ul>
                        <li><a title="Oferta" href="/oferta.html"/>Oferta</a></li>
                        <li><a title="Katalog" href="/katalog.html"/>Katalog</a></li>
                        <li class="last"><a title="Kontakt" href="/kontakt.html"/>Kontakt</a></li>
                        <div class="clear"></div>
                    </ul>
                </div>
    <p class="developed"><a href="https://www.reprezenter.pl/" target="_blank">developed by reprezenter.pl</a></p>
    <div class="clear"></div>
</div>
</div>
</body>

</html>