<!DOCTYPE html>
<html lang="<?php echo $api->langShort(); ?>">
    <head>
        <meta name="robots" content="index, follow">
        <meta charset="utf-8">
        <title><?php echo $api->getMeta('title'); ?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">        

        <meta name="description" content="Opis strony">


        <link href="/css/main.css" media="screen" rel="stylesheet" type="text/css">

        <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon">
        <link rel="icon" href="img/favicon.ico" type="image/x-icon">
    </head>
    <body>
        <div class="contentWrapper">
            <div clas="header">
                <div class="logo">
                    <a href="http://wirtualne-biuro.com.pl" title="Wirtualne biuro">Wirtualne Biuro<span>.com.pl</span></a>
                </div>    
                <a class="hamburger" href="#"><img  src="/img/hamburger.png" alt="menu" /></a>
                <div class="menu">                
                    <ul>
                        <li><a title="O nas" href="/o-nas.html"/>O nas</a></li>
                        <li><a title="Oferta" href="/oferta.html"/>Oferta</a></li>
                        <li><a title="Katalog" href="/katalog.html"/>Katalog</a></li>
                        <li><a title="Kontakt" href="/kontakt.html"/>Kontakt</a></li>
                    </ul>
                </div>
                <div class="clear"></div>
                <div class="banner"></div>
            </div>
            <div class="content">




