<?php $name = 'module_blog_edit'; ?>
<form name="<?php echo $name; ?>" method="POST" action="">
    <div class="formElement">
        <label><?php echo $api->t('Tyuł'); ?></label>
        <input type="text" name="title" value="<?php echo $api->getFormData($name, 'title'); ?>" />
        <?php if ($api->getFormErrors($name, 'title')): ?>
            <div class="error"><?php echo implode(' ', $api->getFormErrors($name, 'title')); ?></div>
        <?php endif; ?>
    </div>
    <div class="formElement">
        <label><?php echo $api->t('Zajawka'); ?></label>
        <textarea name="short_content"><?php echo $api->getFormData($name, 'short_content'); ?></textarea>
        <?php if ($api->getFormErrors($name, 'short_content')): ?>
            <div class="error"><?php echo implode(' ', $api->getFormErrors($name, 'short_content')); ?></div>
        <?php endif; ?>
    </div>
    <div class="formElement">
        <label><?php echo $api->t('Treść'); ?></label>
        <textarea name="content"><?php echo $api->getFormData($name, 'content'); ?></textarea>
        <?php if ($api->getFormErrors($name, 'content')): ?>
            <div class="error"><?php echo implode(' ', $api->getFormErrors($name, 'content')); ?></div>
        <?php endif; ?>
    </div>
    <div class="formElement">
        <label><?php echo $api->t('Kolejność (rosnąco)'); ?></label>
        <input type="text" name="order_id" value="<?php echo $api->getFormData($name, 'order_id', 0); ?>" />
        <?php if ($api->getFormErrors($name, 'order_id')): ?>
            <div class="error"><?php echo implode(' ', $api->getFormErrors($name, 'order_id')); ?></div>
        <?php endif; ?>
    </div>

    <div class="formElement image">
        <label for="blog_form_image">Zdjęcie</label>
        <input type="file" name="image" class="uploader" data-url="/admin/blog/ajax/uploader.html?id=<?php echo $api->getModule('Blog')->getTmpId(); ?>&e_id=<?php echo $api->getModule('Blog')->getEntityId(); ?>" id="blog_form_image">
    </div>            
    <div class="imageGallery"><img src="/img/admin/upload.svg" /></div>
    <div class="formElement">
        <input type="submit" value="<?php echo $api->t('Zapisz'); ?>" name="<?php echo $name; ?>"/>
    </div>
</form>